### ISSUE TITLE
Astro 3 plans to drop support for node 16

### ISSUE THREAD

**Issue by jrencz** [cloudflare/pages-build-image#4]
https://github.com/withastro/astro/releases/tag/astro%403.0.0-beta.0

As mentioned in https://community.cloudflare.com/t/support-node-18-in-pages-or-allow-config/414797/5 there's a way to manually set 18

**Comment by WalshyDev** [comment]
The v2 build system (default version) defaults to Node.js 18. I'd recommend using that.

V1 does also allow selection as you pointed out, this is already very common for those using v1 due to the Node.js 12 default.

So I think the only action item for us here is to update the docs once this is released.

Thanks for pointing this out 🙂
